### **Pandas**
Known as Panel data
This is a python library used for working with data

### Series and Dataframes
#### Series
This is a one dimensional array like object that can hold data

#### Dataframes
This is a two-dimensional labelled data structure with columns that can be of different types

In [1]:
import pandas as pd
#Create a series from a list
S = pd.Series([10,20,30,40,50])
print(S)

#create a series with a custom index
S = pd.Series([10,20,30,40,50],index = ['a','b','c','d','e'])
print(S)

0    10
1    20
2    30
3    40
4    50
dtype: int64
a    10
b    20
c    30
d    40
e    50
dtype: int64

In [5]:
data = {
    'Name':['Alice','Ben','Tracey','Mike','Eva'],
    'Age' :[23,30,18,22,19],
    'City':['Nairobi','Nairobi','Nairobi','Nairobi','Nairobi'],
}
df=pd.DataFrame(data)
print(df)

     Name  Age     City
0   Alice   23  Nairobi
1     Ben   30  Nairobi
2  Tracey   18  Nairobi
3    Mike   22  Nairobi
4     Eva   19  Nairobi

In [10]:
import pandas as pd
df= pd.read_csv('IRIS.csv')

In [2]:
import pandas as pd
df= pd.read_csv('IRIS.csv')
df .info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [3]:
import pandas as pd
df= pd.read_csv('IRIS.csv')
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
import pandas as pd
df= pd.read_csv('IRIS.csv')
df.tail()

     sepal_length  sepal_width  petal_length  petal_width         species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [5]:
import pandas as pd
df= pd.read_csv('IRIS.csv')
df.shape

(150, 5)

In [6]:
import pandas as pd
df= pd.read_csv('IRIS.csv')
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species             str
dtype: object

In [7]:
import pandas as pd
df= pd.read_csv('IRIS.csv')
len(df)

150

In [8]:
import pandas as pd
df= pd.read_csv('IRIS.csv')
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [9]:
import pandas as pd
df= pd.read_csv('IRIS.csv')
df.count()

sepal_length    150
sepal_width     150
petal_length    150
petal_width     150
species         150
dtype: int64

In [2]:
import pandas as pd
df= pd.read_csv('IRIS.csv')
df['species'].unique()

<StringArray>
['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
Length: 3, dtype: str


**Term**                          **Meaning**
Index	                       The label that identifies each row in a DataFrame.
Default index	               0, 1, 2, ... created automatically by pandas.
Set index	                   Replace the default index with a more meaningful column using set_index().
Reset index	                   Restore the default numeric index using reset_index().
Why it matters	               Makes data easier to locate, interpret, join, and analyze efficiently.

In [4]:
import pandas as pd
import numpy as np

In [5]:
# Kenyantech prffesionals dataset
data = {
       'name':         ['Aisha', 'Brian', 'Celestine', 'David', 'Esther', 
                     'Felix', 'Grace', 'Hassan', 'Ivy', 'James', 
                     'Kendi', 'Liban', 'Mary', 'Noel', 'Olive'], 

    'job_title':    ['Data Analyst', 'Software Engineer', 'Data Scientist', 'DevOps Engineer', 'Data Analyst', 
                     'ML Engineer', 'Software Engineer', 'Data Scientist', 'Data Analyst', 'Software Engineer', 
                     'ML Engineer', 'DevOps Engineer', 'Data Scientist', 'Data Analyst', 'Software Engineer'], 

    'city':         ['Nairobi', 'Mombasa', 'Nairobi', 'Kisumu', 'Nairobi', 
                     'Nairobi', 'Mombasa', 'Nairobi', 'Nakuru', 'Nairobi', 
                     'Kisumu', 'Nairobi', 'Mombasa', 'Nairobi', 'Nairobi'], 

    'salary_kes':   [85000, 120000, 150000, 110000, 78000, 
                     175000, 115000, 160000, 72000, 130000, 
                     180000, 105000, 145000, 80000, 125000], 

    'experience_yrs': [2, 4, 5, 3, 1, 6, 4, 7, 1, 5, 7, 3, 6, 2, 4], 

    'employment_type': ['Full-time', 'Full-time', 'Contract', 'Full-time', 'Part-time', 
                        'Full-time', 'Contract', 'Full-time', 'Part-time', 'Full-time', 
                        'Full-time', 'Contract', 'Full-time', 'Full-time', 'Contract'], 

    'age':          [25, 28, 30, 27, 24, 32, 29, 35, 23, 31, 34, 26, 33, 25, 28], 

    'joined_date':  ['2022-03-15', '2020-07-01', '2019-11-20', '2021-05-10', '2023-01-08', 
                     '2018-09-03', '2020-12-15', '2017-04-22', '2023-02-14', '2019-06-30', 
                     '2017-08-11', '2021-03-25', '2018-05-17', '2022-09-01', '2020-11-10'], 
                     
    'salary_history_2022': [70000, 100000, None, 95000, None, 
                             150000, 100000, 140000, None, 115000, 
                             160000, 90000, 130000, 65000, 110000] 
}


df = pd.DataFrame(data)
print(df)

         name          job_title     city  salary_kes  experience_yrs  \
0       Aisha       Data Analyst  Nairobi       85000               2
1       Brian  Software Engineer  Mombasa      120000               4
2   Celestine     Data Scientist  Nairobi      150000               5
3       David    DevOps Engineer   Kisumu      110000               3
4      Esther       Data Analyst  Nairobi       78000               1
5       Felix        ML Engineer  Nairobi      175000               6
6       Grace  Software Engineer  Mombasa      115000               4
7      Hassan     Data Scientist  Nairobi      160000               7
8         Ivy       Data Analyst   Nakuru       72000               1
9       James  Software Engineer  Nairobi      130000               5
10      Kendi        ML Engineer   Kisumu      180000               7
11      Liban    DevOps Engineer  Nairobi      105000               3
12       Mary     Data Scientist  Mombasa      145000               6
13       Noel       Data Analyst  Nairobi       80000               2
14      Olive  Software Engineer  Nairobi      125000               4

   employment_type  age joined_date  salary_history_2022
0        Full-time   25  2022-03-15              70000.0
1        Full-time   28  2020-07-01             100000.0
2         Contract   30  2019-11-20                  NaN
3        Full-time   27  2021-05-10              95000.0
4        Part-time   24  2023-01-08                  NaN
5        Full-time   32  2018-09-03             150000.0
6         Contract   29  2020-12-15             100000.0
7        Full-time   35  2017-04-22             140000.0
8        Part-time   23  2023-02-14                  NaN
9        Full-time   31  2019-06-30             115000.0
10       Full-time   34  2017-08-11             160000.0
11        Contract   26  2021-03-25              90000.0
12       Full-time   33  2018-05-17             130000.0
13       Full-time   25  2022-09-01              65000.0
14        Contract   28  2020-11-10             110000.0

### 1.2: Series and DataFrames
A series is a single column with labels called indexes
Every column in a dataframe is a series 

A dataframe is a full two dimension table - rows and columns , like a spreadsheet

In [6]:
salaries = pd.Series([85000, 120000, 150000,110000,78000])
print(salaries)

0     85000
1    120000
2    150000
3    110000
4     78000
dtype: int64

In [7]:
print(df.head())
print(type(df))

print(df["name"])

        name          job_title     city  salary_kes  experience_yrs  \
0      Aisha       Data Analyst  Nairobi       85000               2
1      Brian  Software Engineer  Mombasa      120000               4
2  Celestine     Data Scientist  Nairobi      150000               5
3      David    DevOps Engineer   Kisumu      110000               3
4     Esther       Data Analyst  Nairobi       78000               1

  employment_type  age joined_date  salary_history_2022
0       Full-time   25  2022-03-15              70000.0
1       Full-time   28  2020-07-01             100000.0
2        Contract   30  2019-11-20                  NaN
3       Full-time   27  2021-05-10              95000.0
4       Part-time   24  2023-01-08                  NaN
<class 'pandas.DataFrame'>
0         Aisha
1         Brian
2     Celestine
3         David
4        Esther
5         Felix
6         Grace
7        Hassan
8           Ivy
9         James
10        Kendi
11        Liban
12         Mary
13         Noel
14        Olive
Name: name, dtype: str

### Creating a DataFrame

In [8]:
# 1. From a dictionary
#Key = Column names : value = lists of data
mini = pd.DataFrame({
    'names':['Aisha','Brian','Joy'],
    'salary':[85000, 120000, 150000],
})
print(mini)

   names  salary
0  Aisha   85000
1  Brian  120000
2    Joy  150000

In [26]:
# 2.From a list of rows
rows =[
    {'name':'Aisha', 'salary':85000},
    {'name':'Brian', 'salary':120000},
    {'name':'Joy', 'salary':150000}
    ]
mini = pd.DataFrame(rows)
print(mini)

#if a dict is missing a key pandas fills that cell with NaN

    name  salary
0  Aisha   85000
1  Brian  120000
2    Joy  150000

### Loading and Saving data

In [ ]:
df = pd.read_csv('jobs.csv') #loads csv
df = pd.read_excel('jobs.xlsx', sheet_name='Sheet1') #loads excel
df.to_csv('cleaned_jobs.csv', index=False) #saves csv(no row numbers)

### Inspecting the data
Always look at your data before doing anything with it

### Index
The index is the label for each row

In [ ]:
# DATA INSPECTION IN PANDAS

# View the first 5 rows
df.head()

# View the last 5 rows
df.tail()

# Display information about the DataFrame
df.info()

# Summary statistics for numerical columns
df.describe()

# Summary statistics for categorical/text columns
df.describe(include='object')

# Display the number of rows and columns
df.shape

# Display column names
df.columns

# Display row index labels
df.index

# Display the data type of each column
df.dtypes

# Display random row(s)
df.sample()

# Check for missing values
df.isnull()

# Count missing values in each column
df.isnull().sum()

# Check for non-missing values
df.notnull()

# Identify duplicate rows
df.duplicated()

# Count duplicate rows
df.duplicated().sum()

# Count unique values in each column
df.nunique()

# Display unique values in a specific column
df['column_name'].unique()

# Count occurrences of each unique value
df['column_name'].value_counts()

# Display memory usage of each column
df.memory_usage()

In [24]:
print(df.index) #Range index (start = 0 , stop = 15, step=1)

df_indexed = df.set_index('name')  #set namr column as index
print(df_indexed.loc['Aisha'])     #get Aisha's full roe

df_indexed = df_indexed.reset_index()  #reset back to numbers

RangeIndex(start=0, stop=15, step=1)
job_title              Data Analyst
city                        Nairobi
salary_kes                    85000
experience_yrs                    2
employment_type           Full-time
age                              25
joined_date              2022-03-15
salary_history_2022         70000.0
had_missing_salary            False
Name: Aisha, dtype: object

In [23]:
#When we merge tables pr dp some operations between 2 series , pandas aligns
#data by index labels,if the labels dont match you get NaN
s1 = pd.Series([100 , 200], index = ['Nairobi','Mombasa'])
s2 = pd.Series([50 , 75], index = ['Mombasa','Kisumu'])
print(s1 + s2)

Kisumu       NaN
Mombasa    250.0
Nairobi      NaN
dtype: float64

### Accessing and selecting columns

In [22]:
# Selecting columns
df['salary_kes']
df[['name','salary_kes','city']]

         name  salary_kes     city
0       Aisha       85000  Nairobi
1       Brian      120000  Mombasa
2   Celestine      150000  Nairobi
3       David      110000   Kisumu
4      Esther       78000  Nairobi
5       Felix      175000  Nairobi
6       Grace      115000  Mombasa
7      Hassan      160000  Nairobi
8         Ivy       72000   Nakuru
9       James      130000  Nairobi
10      Kendi      180000   Kisumu
11      Liban      105000  Nairobi
12       Mary      145000  Mombasa
13       Noel       80000  Nairobi
14      Olive      125000  Nairobi

In [21]:
# Selecting rows : loc and iloc
#loc - uses labels(row index values , column names). Slice end in inclusive
#iloc - use positions- postion based(numbers like a list). Slice end is exclusive

#iloc - position based
df.iloc[0]
df.iloc[0:3]

,name,job_title,city,salary_kes,experience_yrs,employment_type,age,joined_date,salary_history_2022,had_missing_salary
0,Aisha,Data Analyst,Nairobi,85000,2,Full-time,25,2022-03-15,70000.0,False
1,Brian,Software Engineer,Mombasa,120000,4,Full-time,28,2020-07-01,100000.0,False
2,Celestine,Data Scientist,Nairobi,150000,5,Contract,30,2019-11-20,105000.0,True

In [20]:
#loc - label based
df.loc[0] #row with label 0
df.loc[0:4] #labels 0 to 4 inclusive
df.loc[0:4,'name':'city'] # columns from name to city inclusive of city

        name          job_title     city
0      Aisha       Data Analyst  Nairobi
1      Brian  Software Engineer  Mombasa
2  Celestine     Data Scientist  Nairobi
3      David    DevOps Engineer   Kisumu
4     Esther       Data Analyst  Nairobi

In [19]:
# combining rows and columns
df.loc[2:5,['name','salary_kes']]

        name  salary_kes
2  Celestine      150000
3      David      110000
4     Esther       78000
5      Felix      175000

In [18]:
df.iloc[:10,[0,2,3]]

        name     city  salary_kes
0      Aisha  Nairobi       85000
1      Brian  Mombasa      120000
2  Celestine  Nairobi      150000
3      David   Kisumu      110000
4     Esther  Nairobi       78000
5      Felix  Nairobi      175000
6      Grace  Mombasa      115000
7     Hassan  Nairobi      160000
8        Ivy   Nakuru       72000
9      James  Nairobi      130000

In [17]:
df.iloc[0:4]
df.loc[0:4]

,name,job_title,city,salary_kes,experience_yrs,employment_type,age,joined_date,salary_history_2022,had_missing_salary
0,Aisha,Data Analyst,Nairobi,85000,2,Full-time,25,2022-03-15,70000.0,False
1,Brian,Software Engineer,Mombasa,120000,4,Full-time,28,2020-07-01,100000.0,False
2,Celestine,Data Scientist,Nairobi,150000,5,Contract,30,2019-11-20,105000.0,True
3,David,DevOps Engineer,Kisumu,110000,3,Full-time,27,2021-05-10,95000.0,False
4,Esther,Data Analyst,Nairobi,78000,1,Part-time,24,2023-01-08,105000.0,True

In [16]:
# Filterning rows (boolean conditions)
#Write a condition that returns True/False

#Employees earning over 100000
df[df['salary_kes'] > 100000]

#Data Analyst only
df[df['job_title'] =='Data Analyst']

#Nairobi employees earning over 100k
df[(df['city'] == 'Nairobi') & (df['salary_kes'] > 100000)]

#Data Analysts or ML engineers
df[(df['job_title'] == 'Data Analyst') | (df['job_title'] == 'ML Engineer')]

#Everyone who is not on contract
df[df['employment_type'] != "Contract"]

,name,job_title,city,salary_kes,experience_yrs,employment_type,age,joined_date,salary_history_2022,had_missing_salary
0,Aisha,Data Analyst,Nairobi,85000,2,Full-time,25,2022-03-15,70000.0,False
1,Brian,Software Engineer,Mombasa,120000,4,Full-time,28,2020-07-01,100000.0,False
3,David,DevOps Engineer,Kisumu,110000,3,Full-time,27,2021-05-10,95000.0,False
4,Esther,Data Analyst,Nairobi,78000,1,Part-time,24,2023-01-08,105000.0,True
5,Felix,ML Engineer,Nairobi,175000,6,Full-time,32,2018-09-03,150000.0,False
7,Hassan,Data Scientist,Nairobi,160000,7,Full-time,35,2017-04-22,140000.0,False
8,Ivy,Data Analyst,Nakuru,72000,1,Part-time,23,2023-02-14,105000.0,True
9,James,Software Engineer,Nairobi,130000,5,Full-time,31,2019-06-30,115000.0,False
10,Kendi,ML Engineer,Kisumu,180000,7,Full-time,34,2017-08-11,160000.0,False
12,Mary,Data Scientist,Mombasa,145000,6,Full-time,33,2018-05-17,130000.0,False
13,Noel,Data Analyst,Nairobi,80000,2,Full-time,25,2022-09-01,65000.0,False

In [15]:
#filtering with isin
# when you want to match against a list of values
df[df['job_title'].isin(['Data Analyst', 'ML Engineer'])]
df[df['city'].isin(['Mombasa', 'Kisumu'])]

,name,job_title,city,salary_kes,experience_yrs,employment_type,age,joined_date,salary_history_2022,had_missing_salary
1,Brian,Software Engineer,Mombasa,120000,4,Full-time,28,2020-07-01,100000.0,False
3,David,DevOps Engineer,Kisumu,110000,3,Full-time,27,2021-05-10,95000.0,False
6,Grace,Software Engineer,Mombasa,115000,4,Contract,29,2020-12-15,100000.0,False
10,Kendi,ML Engineer,Kisumu,180000,7,Full-time,34,2017-08-11,160000.0,False
12,Mary,Data Scientist,Mombasa,145000,6,Full-time,33,2018-05-17,130000.0,False

## HANDLING MISSING VALUES
### **Flagging Missing Values**
It creates an indicator showing which values were originally missing.
Instead of only filling the missing values, you create another column showing where data was originally missing.
df["Age_missing"] = df["Age"].isnull()
df["Age_missing"] = df["Age"].isna()

*Why flag missing values?*
Sometimes missing values are meaningful.

### **Interpolation**
Interpolation is the process of estimating missing values based on the values around them.
Interpolation assumes that the missing value follows the trend of the surrounding data.

#### Types of interpolation
1. Linear interpolation
Assumes data changes in a straight line.

2. Polynomial interpolation
Uses a curved line rather than a straight line.
Useful when data naturally curves.

3. Time interpolation
Useful for time series.

### **Replacing Missing Values/Imputation**
Means filling NaN values with something else.

You can replace with:
                     Mean
                     Median
                     Mode
                     Constant value
                     Previous value
                     Next value
                     Predicted value from a machine learning model

###  **Simple Imputer**
SimpleImputer is a class from scikit-learn that automatically replaces missing values using a chosen strategy.
Automates imputation using strategies like mean, median, mode, or a constant

*Why use SimpleImputer?*
It integrates well into machine learning workflows, especially when building preprocessing pipelines.

### **Forward Fill (ffill)**
Forward fill copies the previous valid value into the missing value.
df.ffill()
df.fillna(method="ffill")

*Advantages*
Very fast
Good for time series data
Preserves previous observations

*Disadvantages*
Can repeat outdated values if there are many consecutive missing entries

### **Backward Fill (bfill)**
Backward fill copies the next valid value backward into missing entries.
Use the next available value.
df.bfill()
df.fillna(method="bfill")

*Advantages*
Useful when later observations are more appropriate than earlier ones
Common in some time series or ordered datasets

*Disadvantages*
May use future information, which is not always appropriate (for example, in forecasting tasks)

In [14]:
# Detecting the missing value
# Missing values in pandas show up as NaN
# We find them first then decide what to do

df.isna()
df.isna().sum() #Count of missing per column
df['salary_history_2022'].isna()

# filter rows where a value is missing
df[df['salary_history_2022'].isna()]

# filter rows where a value is not missing
df[df['salary_history_2022'].notna()]

,name,job_title,city,salary_kes,experience_yrs,employment_type,age,joined_date,salary_history_2022,had_missing_salary
0,Aisha,Data Analyst,Nairobi,85000,2,Full-time,25,2022-03-15,70000.0,False
1,Brian,Software Engineer,Mombasa,120000,4,Full-time,28,2020-07-01,100000.0,False
2,Celestine,Data Scientist,Nairobi,150000,5,Contract,30,2019-11-20,105000.0,True
3,David,DevOps Engineer,Kisumu,110000,3,Full-time,27,2021-05-10,95000.0,False
4,Esther,Data Analyst,Nairobi,78000,1,Part-time,24,2023-01-08,105000.0,True
5,Felix,ML Engineer,Nairobi,175000,6,Full-time,32,2018-09-03,150000.0,False
6,Grace,Software Engineer,Mombasa,115000,4,Contract,29,2020-12-15,100000.0,False
7,Hassan,Data Scientist,Nairobi,160000,7,Full-time,35,2017-04-22,140000.0,False
8,Ivy,Data Analyst,Nakuru,72000,1,Part-time,23,2023-02-14,105000.0,True
9,James,Software Engineer,Nairobi,130000,5,Full-time,31,2019-06-30,115000.0,False
10,Kendi,ML Engineer,Kisumu,180000,7,Full-time,34,2017-08-11,160000.0,False
11,Liban,DevOps Engineer,Nairobi,105000,3,Contract,26,2021-03-25,90000.0,False
12,Mary,Data Scientist,Mombasa,145000,6,Full-time,33,2018-05-17,130000.0,False
13,Noel,Data Analyst,Nairobi,80000,2,Full-time,25,2022-09-01,65000.0,False
14,Olive,Software Engineer,Nairobi,125000,4,Contract,28,2020-11-10,110000.0,False

In [13]:
# Dropping missing values
# Use this when the rows or columns with missing data are not useful
  
df.dropna()           # drops any row with at least one missing value
df.dropna(how='all')  # drops only if the entire row is NaN
df.dropna(subset=['salary_history_2022'])  #drops rows where the columns is NaN
df.dropna(axis = 1)      #drops columns that have any NaN values
df.dropna(thresh = 8)    # keeps rows with at least 8 NaN values

,name,job_title,city,salary_kes,experience_yrs,employment_type,age,joined_date,salary_history_2022,had_missing_salary
0,Aisha,Data Analyst,Nairobi,85000,2,Full-time,25,2022-03-15,70000.0,False
1,Brian,Software Engineer,Mombasa,120000,4,Full-time,28,2020-07-01,100000.0,False
2,Celestine,Data Scientist,Nairobi,150000,5,Contract,30,2019-11-20,105000.0,True
3,David,DevOps Engineer,Kisumu,110000,3,Full-time,27,2021-05-10,95000.0,False
4,Esther,Data Analyst,Nairobi,78000,1,Part-time,24,2023-01-08,105000.0,True
5,Felix,ML Engineer,Nairobi,175000,6,Full-time,32,2018-09-03,150000.0,False
6,Grace,Software Engineer,Mombasa,115000,4,Contract,29,2020-12-15,100000.0,False
7,Hassan,Data Scientist,Nairobi,160000,7,Full-time,35,2017-04-22,140000.0,False
8,Ivy,Data Analyst,Nakuru,72000,1,Part-time,23,2023-02-14,105000.0,True
9,James,Software Engineer,Nairobi,130000,5,Full-time,31,2019-06-30,115000.0,False
10,Kendi,ML Engineer,Kisumu,180000,7,Full-time,34,2017-08-11,160000.0,False
11,Liban,DevOps Engineer,Nairobi,105000,3,Contract,26,2021-03-25,90000.0,False
12,Mary,Data Scientist,Mombasa,145000,6,Full-time,33,2018-05-17,130000.0,False
13,Noel,Data Analyst,Nairobi,80000,2,Full-time,25,2022-09-01,65000.0,False
14,Olive,Software Engineer,Nairobi,125000,4,Contract,28,2020-11-10,110000.0,False

In [33]:

# Fill all missing values in the DataFrame with a placeholder
df = df.fillna('Unknown')

# Fill numeric column with the median
median_val = df['salary_history_2022'].median()
df['salary_history_2022'] = df['salary_history_2022'].fillna(median_val)

# Fill text column with the most common value (mode)
df['employment_type'] = df['employment_type'].fillna(df['employment_type'].mode()[0])

# Forward fill
df['salary_history_2022'] = df['salary_history_2022'].ffill()
# df['salary_history_2022'].fillna(method='ffill', inplace=True)

# Backward fill
df['salary_history_2022'] = df['salary_history_2022'].bfill()
# df['salary_history_2022'].fillna(method='bfill', inplace=True)

In [11]:
#Interpolation
#For numeric columns in sequence , estimate the missing values
df['salary_history_2022'].interpolate(method='linear', inplace=True)

# Flagging that a value is missing
# One might want to keep the record that the value was originally missing

df['had_missing_salary']= df['salary_history_2022'].isna()
df['salary_history_2022'] = df['salary_history_2022'].fillna(df['salary_history_2022'].median())

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4868\2479555444.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['salary_history_2022'].interpolate(method='linear', inplace=True)

### Cleaning and Transforming Data

In [ ]:
# Checking and Converting Data Types
# When you load data , columns dont always come in the right 
# Numbers might be stored as strings,dates as

Adding and modifying columns
Renaming columns
Dropping columns and rows
Sorting
Datetime operations
Binning - grouping numbers into categories
One-hot encoding

### Grouping and aggregation

#### Group by
It wrks in 3 steps 
split - divides the data into groups
apply - runs a function on each group
combine - brings the result together
'for each[category],calculate[something]'

In [27]:
df.groupby('job_title')['salary_kes'].mean()  #average salary per role
df.groupby('city')['name'].count()            #headcount per city
df.groupby('employment_type')['salary_kes'].max()

employment_type
Contract     150000
Full-time    180000
Part-time     78000
Name: salary_kes, dtype: int64

In [ ]:
# Common aggregation functions
df.groupby('job_title')['salary_kes'].mean()  #average
df.groupby('job_title')['salary_kes'].max     #highest value
df.groupby('job_title')['salary_kes'].min()   #lowest value
df.groupby('job_title')['salary_kes'].std()   #std deviation
df.groupby('job_title')['salary_kes'].count()  #non-null count
df.groupby('job_title')['salary_kes'].sum()  #average salary per role
df.groupby('job_title')['salary_kes'].median()  #middke
df.groupby('job_title')['salary_kes'].size()  #group size , all rows

#### Multiple Statistics at Once

In [28]:
df.groupby('job_title')['salary_kes'].agg(['mean', 'median', 'min', 'max', 'count'])

# Different stats for different columns
df.groupby('job_title').agg({
 'salary_kes': ['mean', 'max'],
 'experience_yrs': ['mean', 'min'],
 'age': 'median'
})

                      salary_kes         experience_yrs        age
                            mean     max           mean min median
job_title
Data Analyst        78750.000000   85000           1.50   1   24.5
Data Scientist     151666.666667  160000           6.00   5   33.0
DevOps Engineer    107500.000000  110000           3.00   3   26.5
ML Engineer        177500.000000  180000           6.50   6   33.0
Software Engineer  122500.000000  130000           4.25   4   28.5

#### Grouping by Multiple Columns

In [29]:
df.groupby(['city', 'employment_type'])['salary_kes'].mean()
df.groupby(['job_title', 'city']).agg({
 'salary_kes': 'mean',
 'experience_yrs': 'mean'
})

                           salary_kes  experience_yrs
job_title         city
Data Analyst      Nairobi     81000.0        1.666667
                  Nakuru      72000.0        1.000000
Data Scientist    Mombasa    145000.0        6.000000
                  Nairobi    155000.0        6.000000
DevOps Engineer   Kisumu     110000.0        3.000000
                  Nairobi    105000.0        3.000000
ML Engineer       Kisumu     180000.0        7.000000
                  Nairobi    175000.0        6.000000
Software Engineer Mombasa    117500.0        4.000000
                  Nairobi    127500.0        4.500000

#### Pivot Tables
Pivot tables do the same thing as GroupBy but lay the results out as a 2D grid — rows vs columns. Great when you want to 
compare two categories at once.

In [30]:
pd.pivot_table(
 df,
 values='salary_kes',
 index='job_title',
 columns='city',
 aggfunc='mean',
 fill_value=0
)

city                 Kisumu   Mombasa   Nairobi   Nakuru
job_title
Data Analyst            0.0       0.0   81000.0  72000.0
Data Scientist          0.0  145000.0  155000.0      0.0
DevOps Engineer    110000.0       0.0  105000.0      0.0
ML Engineer        180000.0       0.0  175000.0      0.0
Software Engineer       0.0  117500.0  127500.0      0.0

In [31]:
# With row/column totals
pd.pivot_table(
 df,
 values='salary_kes',
 index='job_title',
 columns='employment_type',
 aggfunc='mean',
 margins=True,
 margins_name='Overall Avg'
)

employment_type    Contract      Full-time  Part-time    Overall Avg
job_title
Data Analyst            NaN   82500.000000    75000.0   78750.000000
Data Scientist     150000.0  152500.000000        NaN  151666.666667
DevOps Engineer    105000.0  110000.000000        NaN  107500.000000
ML Engineer             NaN  177500.000000        NaN  177500.000000
Software Engineer  120000.0  125000.000000        NaN  122500.000000
Overall Avg        123750.0  131666.666667    75000.0  122000.000000

### Cross-Tabulation — Counting Combinations
crosstab counts how many times each combination of two categories appears together.

In [32]:
pd.crosstab(df['city'], df['job_title'])
pd.crosstab(df['city'], df['job_title'], margins=True) # with totals
pd.crosstab(df['city'], df['job_title'], normalize='index') * 100 # row

job_title,Data Analyst,Data Scientist,DevOps Engineer,ML Engineer,Software Engineer
city,,,,,
Kisumu,0.000000,0.000000,50.000000,50.000000,0.000000
Mombasa,0.000000,33.333333,0.000000,0.000000,66.666667
Nairobi,33.333333,22.222222,11.111111,11.111111,22.222222
Nakuru,100.000000,0.000000,0.000000,0.000000,0.000000

### Merging and Combining Data Sets
Merging combines two DataFrames based on a shared column — exactly like SQL JOINs.

In [36]:
departments = pd.DataFrame({
 'job_title': ['Data Analyst', 'Software Engineer', 'Data Scientist', 'ML Engineer', 
'DevOps Engineer'],
 'department': ['Analytics', 'Engineering', 'Analytics', 'AI/ML', 'Infrastructure'],
 'budget_kes': [5000000, 8000000, 6000000, 9000000, 7000000]
})
print(departments)

# Inner join — only rows where job_title exists in BOTH tables
merged = pd.merge(df, departments, on='job_title', how='inner')
print(merged)

           job_title      department  budget_kes
0       Data Analyst       Analytics     5000000
1  Software Engineer     Engineering     8000000
2     Data Scientist       Analytics     6000000
3        ML Engineer           AI/ML     9000000
4    DevOps Engineer  Infrastructure     7000000
         name          job_title     city  salary_kes  experience_yrs  \
0       Aisha       Data Analyst  Nairobi       85000               2
1       Brian  Software Engineer  Mombasa      120000               4
2   Celestine     Data Scientist  Nairobi      150000               5
3       David    DevOps Engineer   Kisumu      110000               3
4      Esther       Data Analyst  Nairobi       78000               1
5       Felix        ML Engineer  Nairobi      175000               6
6       Grace  Software Engineer  Mombasa      115000               4
7      Hassan     Data Scientist  Nairobi      160000               7
8         Ivy       Data Analyst   Nakuru       72000               1
9       James  Software Engineer  Nairobi      130000               5
10      Kendi        ML Engineer   Kisumu      180000               7
11      Liban    DevOps Engineer  Nairobi      105000               3
12       Mary     Data Scientist  Mombasa      145000               6
13       Noel       Data Analyst  Nairobi       80000               2
14      Olive  Software Engineer  Nairobi      125000               4

   employment_type  age joined_date  salary_history_2022  had_missing_salary  \
0        Full-time   25  2022-03-15              70000.0               False
1        Full-time   28  2020-07-01             100000.0               False
2         Contract   30  2019-11-20             105000.0                True
3        Full-time   27  2021-05-10              95000.0               False
4        Part-time   24  2023-01-08             105000.0                True
5        Full-time   32  2018-09-03             150000.0               False
6         Contract   29  2020-12-15             100000.0               False
7        Full-time   35  2017-04-22             140000.0               False
8        Part-time   23  2023-02-14             105000.0                True
9        Full-time   31  2019-06-30             115000.0               False
10       Full-time   34  2017-08-11             160000.0               False
11        Contract   26  2021-03-25              90000.0               False
12       Full-time   33  2018-05-17             130000.0               False
13       Full-time   25  2022-09-01              65000.0               False
14        Contract   28  2020-11-10             110000.0               False

        department  budget_kes
0        Analytics     5000000
1      Engineering     8000000
2        Analytics     6000000
3   Infrastructure     7000000
4        Analytics     5000000
5            AI/ML     9000000
6      Engineering     8000000
7        Analytics     6000000
8        Analytics     5000000
9      Engineering     8000000
10           AI/ML     9000000
11  Infrastructure     7000000
12       Analytics     6000000
13       Analytics     5000000
14     Engineering     8000000

In [37]:
# The four types of joins
pd.merge(df, departments, on='job_title', how='inner') # only matching rows
pd.merge(df, departments, on='job_title', how='left') # all left + NaN for missing right
pd.merge(df, departments, on='job_title', how='right') # all right + NaN for missing left
pd.merge(df, departments, on='job_title', how='outer') # all rows from both

,name,job_title,city,salary_kes,experience_yrs,employment_type,age,joined_date,salary_history_2022,had_missing_salary,department,budget_kes
0,Aisha,Data Analyst,Nairobi,85000,2,Full-time,25,2022-03-15,70000.0,False,Analytics,5000000
1,Esther,Data Analyst,Nairobi,78000,1,Part-time,24,2023-01-08,105000.0,True,Analytics,5000000
2,Ivy,Data Analyst,Nakuru,72000,1,Part-time,23,2023-02-14,105000.0,True,Analytics,5000000
3,Noel,Data Analyst,Nairobi,80000,2,Full-time,25,2022-09-01,65000.0,False,Analytics,5000000
4,Celestine,Data Scientist,Nairobi,150000,5,Contract,30,2019-11-20,105000.0,True,Analytics,6000000
5,Hassan,Data Scientist,Nairobi,160000,7,Full-time,35,2017-04-22,140000.0,False,Analytics,6000000
6,Mary,Data Scientist,Mombasa,145000,6,Full-time,33,2018-05-17,130000.0,False,Analytics,6000000
7,David,DevOps Engineer,Kisumu,110000,3,Full-time,27,2021-05-10,95000.0,False,Infrastructure,7000000
8,Liban,DevOps Engineer,Nairobi,105000,3,Contract,26,2021-03-25,90000.0,False,Infrastructure,7000000
9,Felix,ML Engineer,Nairobi,175000,6,Full-time,32,2018-09-03,150000.0,False,AI/ML,9000000
10,Kendi,ML Engineer,Kisumu,180000,7,Full-time,34,2017-08-11,160000.0,False,AI/ML,9000000
11,Brian,Software Engineer,Mombasa,120000,4,Full-time,28,2020-07-01,100000.0,False,Engineering,8000000
12,Grace,Software Engineer,Mombasa,115000,4,Contract,29,2020-12-15,100000.0,False,Engineering,8000000
13,James,Software Engineer,Nairobi,130000,5,Full-time,31,2019-06-30,115000.0,False,Engineering,8000000
14,Olive,Software Engineer,Nairobi,125000,4,Contract,28,2020-11-10,110000.0,False,Engineering,8000000

In [ ]:
#bJoining on columns with different names
pd.merge(df, other_df, left_on='job_title', right_on='role', how='inner')

### pd.concat() — Stacking DataFrames
When you want to stack tables on top of each other (more rows) or side by side (more columns).

In [ ]:
# Stack rows vertically
nairobi_staff = df[df['city'] == 'Nairobi'].copy()
mombasa_staff = df[df['city'] == 'Mombasa'].copy()
all_staff = pd.concat([nairobi_staff, mombasa_staff], axis=0, ignore_index=True)

# Stack columns horizontally
extra_info = pd.DataFrame({
 'linkedin_url': ['linkedin.com/in/' + name.lower() for name in df['name']]
})
df_extended = pd.concat([df, extra_info], axis=1)